[package]
name = "payments_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
rust_decimal = "1.35.0"
rust_decimal_macros = "1.35.0"
anyhow = "1.0.86"

[dev-dependencies]
tempfile = "3.10.1"
rand = "0.8.5"